[18.0][MIG] connector
thienvh332/connector pull request #1
Opened 2024-09-19 05:04 UTC by thienvh332

2024-09-20 06:25 UTC, nilshamerlinck commented on connector/components/binder.py
> +                (self._external_field, "=", tools.ustr(external_id)),
`tools.ustr` is deprecated, see `https://github.com/odoo/odoo/pull/173811`

2024-09-23 09:36 UTC, nguyenminhchien requested changes
Migrate `test_connector` as well: 1 PR for 2 modules

2024-09-24 05:09 UTC, thienvh332 commented
Hi @nguyenminhchien ,
As I mentioned in **`PR [18.0][MIG] component: Migration to 18.0`** PR for **`test_connector`** at [this link](https://github.com/thienvh332/connector/pull/4)

2024-09-24 09:04 UTC, nguyenminhchien requested changes
I faced some warnings. Please fix them

```
2024-09-24 09:03:05,829 168545 WARNING v18c_connector odoo.addons.base.models.ir_model: Rule access_test_backend has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2024-09-24 09:03:05,829 168545 WARNING v18c_connector odoo.addons.base.models.ir_model: Rule access_connector_test_record has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2024-09-24 09:03:05,829 168545 WARNING v18c_connector odoo.addons.base.models.ir_model: Rule access_connector_test_binding has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
2024-09-24 09:03:05,829 168545 WARNING v18c_connector odoo.addons.base.models.ir_model: Rule access_no_inherits_binding has no group, this is a deprecated feature. Every access-granting rule should specify a group. 
```

2024-09-30 03:35 UTC, nguyenminhchien approved these changes

2024-10-08 07:43 UTC, closed without merging