[18.0][MIG] component: Migration to 18.0
thienvh332/connector pull request #2
Opened 2024-09-19 10:05 UTC by thienvh332

2024-09-23 09:06 UTC, nguyenminhchien requested changes
- Commit message for pre-commit stuff: should follow the format "[IMP] $module: pre-commit auto fixes".
- Migrate the module `test_component` as well: 1 PR for 2 modules.

2024-09-24 05:07 UTC, thienvh332 commented
Hi @nguyenminhchien ,
Thanks for your review.
I think we should separate at module level. So I created a separate PR migration for **`test_component`**. ([Link here](https://github.com/thienvh332/connector/pull/5))

2024-09-24 08:55 UTC, nguyenminhchien approved these changes

2024-09-24 09:09 UTC, nguyenminhchien requested changes

2024-09-24 09:09 UTC, nguyenminhchien commented on test_component/security/ir.model.access.csv
> +access_test_component_collection,access_test_component_collection,model_test_component_collection,,1,1,1,1
Please add a group for this access right. otherwise, we could face an warning:
```
Rule access_test_component_collection has no group, this is a deprecated feature. Every access-granting rule should specify a group
```

2024-09-25 08:19 UTC, nguyenminhchien approved these changes

2024-10-08 07:17 UTC, closed without merging